name: Checkmarx One Scan
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: checkmarx-global-services-internal
          base_uri: https://deu.ast.checkmarx.net/
          additional_params: --apikey ${{ secrets.CX_APIKEY }} --debug
